### ISSUE TITLE
[FEATURE] Improvement - footer text update

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9293] opened 2023-10-03 13:51 UTC
### Description

In the footer, please update **"Road map"** to **"BioDrop Roadmap"**

This will standardize the language in the footer for both the open source roadmap and biodrop roadmaps to increase consistency and clarity.

### Screenshots

![footer](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/ecadfbb7-3bd8-4f55-adfd-c734a31e2d5c)

### Do you want to work on this issue?

No

**Comment by mohak34** [comment] 2023-10-03 13:51
@amandamartin-dev Kindly assign this issue to me so i can work on this

**Comment by PradeepG-07** [comment] 2023-10-03 14:02
Assign to me please

**Comment by SaraJaoude** [comment] 2023-10-03 14:41
> amandamartin-dev Kindly assign this issue to me so i can work on this

@mohak34 - I have assigned this to you as you were the first to ask.  In future please do not tag a specific maintainer - all maintainers are notified and can assign issues.

**Comment by vatsalya-vyas** [comment] 2023-10-07 21:13
@amandamartin-dev Can you assign me to this issue, please?

**Comment by SaraJaoude** [comment] 2023-10-08 08:51
> amandamartin-dev Can you assign me to this issue, please?

@vatsalya-vyas as you can see from the top right of the page under the `Assignees` box this issue is currently assigned to someone else.  Please consider this in future as your comment adds extra noise and notifications.  Also, please avoid tagging a specific maintainer - all maintainers can assign.

**Comment by Aditya7pandey** [comment] 2023-10-20 12:22
May I solve this issue please assign this to me.

**Comment by SaraJaoude** [comment] 2023-10-21 09:40
As there has been no activity on the PR @mohak34 I am unassigning this from you.

> May I solve this issue please assign this to me.

@Aditya7pandey I will assign this to you

**Comment by KshitizRana** [comment] 2023-10-21 14:46
May I solve this issue Please assign this to me.

**Comment by SaraJaoude** [comment] 2023-10-22 09:51
> May I solve this issue Please assign this to me.

@KshitizRana in future please check the history and also the assignees box before asking to be assigned an issue, as this reduces noise and extra notifications. The issue is assigned to someone else.

**Closed** 2023-10-23 05:58 UTC
Labels: ⭐ goal: addition, good first issue, 🔢 points: 1, Hacktoberfest
