### ISSUE TITLE
[OTHER] <Enhancement>

### ISSUE THREAD

**Issue by akshaykaluse35** [EddieHubCommunity/BioDrop#9465] opened 2023-10-12 14:26 UTC
### What would you like to share?

![image](https://github.com/EddieHubCommunity/BioDrop/assets/69835893/7096ee30-1019-49d0-b056-76a15ed30988)
The banner is not looking so good, it stretch to the frame. We can make the banner more interesting  and more good looking 

### Do you want to work on this issue?

Yes

**Comment by amandamartin-dev** [comment] 2023-10-12 15:49
This is a duplicate of #9451  - will close

**Closed by amandamartin-dev** 2023-10-12 15:49 UTC
Labels: 🚦 status: awaiting triage
