### ISSUE TITLE
[BUG] <description>

### ISSUE THREAD

**Issue by MustaphaArfa00** [EddieHubCommunity/BioDrop#10351] opened 2024-04-23 19:36 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

2.100.2

### Description

 Upon upgrading to BioDro Premium, a message displays "You are now a premium user" to users without receiving the 30-day trial period as promised. Instead of displaying an error message, the system inaccurately confirms premium status without initiating the trial, leading to confusion and a lack of a trial for users.

### Steps to Reproduce

Click the "Upgrade" button to proceed.
Upon clicking, you'll be redirected to a new page.
On this page, you'll encounter an offer to try BioDro Premium with a 30-day trial period before subscription at $5/month.
You'll see the option to "Start Freely". Upon selecting this, you can input your email address. A message will confirm your trial's duration until 23/05/2023(which is 1 month from today ).
After entering your email, a green button will activate with the message "You are now a premium user". However, the trial isn't activated as expected.
Rather than showing an error message, the page displays "You are now a premium user" despite the trial not being activated.

### Screenshots

![chrome_cGZlZxt573](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/3d1c9043-f012-4791-b644-2b96c26b54f6)
![chrome_ereYGQpg2G](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/8b7eb6ab-2127-4972-b676-899e59c01a99)
![chrome_8PUPf0qJIq](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/a8650127-435c-4568-ba0f-d62423a0046b)
![image](https://github.com/EddieHubCommunity/BioDrop/assets/156587287/77710529-2553-4ac0-a4da-59ff65d94310)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment] 2024-04-29 12:10
Thank you for raising - this appears to be a duplicate of your other issue https://github.com/EddieHubCommunity/BioDrop/issues/10352 so I shall close this one

**Closed by SaraJaoude** 2024-04-29 12:10 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
