### ISSUE TITLE
[FEATURE] <description>

### ISSUE THREAD

**Issue by arkohaddoebenezer** [EddieHubCommunity/BioDrop#10242] opened 2024-02-25 16:58 UTC
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I'm honestly not sure if this is a feature or a bug, but I think is more of a feature.
The issue is after creating a link I needed to edit the url and is not allowed. 
I can't edit URL of my existing links.
Yet I do not know if it's a premium feature since I use free tier. In that case then, This should be considered a bug for not indicating that editing url is a premium feature.
Otherwise mistakes happens and its good to allow correction

### Proposed Solution

Enable editing url of existing links

### Screenshots

![Screenshot (88)](https://github.com/EddieHubCommunity/BioDrop/assets/46085267/d0c897a4-f17f-4e60-ad5e-9b84c508dd9b)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment] 2024-02-27 08:21
As this appears to be a duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/10243 I will close this Issue.

**Closed by SaraJaoude** 2024-02-27 08:21 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
