### ISSUE TITLE
[FEAT] profile icon does not appear

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/BioDrop#7846] opened 2023-06-29 14:07 UTC
### Description

I was exploring the new version of my Linkfree profile and noticed that the profile pic of the person who gave me a testimonial is no longer there.

EDIT: when managing testimonials the profile picture of the author is not shown as it is on the public profile

### Screenshots

![Profile pic does not appear in testimonial section](https://github.com/EddieHubCommunity/LinkFree/assets/105683440/7e5cd9f3-bb96-4764-a2c0-ffb74cae9790)

### Additional information

I’m open to collaborating with someone on this issue ~~once I solve #7844~~ (this is misleading as it appears that this issue is dependent on the other issue, which it is not).

**Comment by SaraJaoude** [comment] 2023-06-30 12:24
Thanks for raising, however this is not a bug - it was purposely designed this way to keep this page simple when building first time round. 

However this can be added as an enhancement.

**Comment by CBID2** [comment] 2023-06-30 12:40
> Thanks for raising, however this is not a bug - it was purposely designed this way to keep this page simple when building first time round. 
> 
> 
> 
> However this can be added as an enhancement. 

Ohh I see thanks for bringing this up.

**Comment by CBID2** [comment] 2023-07-01 19:04
Hey there. I just wanted to let you know that the profile pic appears now. 
![Profile pic shows up](https://github.com/EddieHubCommunity/LinkFree/assets/105683440/4db88d84-bb83-443c-9c0c-f36111e3f73f).

**Comment by SaraJaoude** [comment] 2023-07-02 01:43
> Hey there. I just wanted to let you know that the profile pic appears now.

 Feel free to close the issue if you like.

@CBID2 could you please clarify? The screenshot you sent in your last message appears to be part of your `public profile` page.  However the Issue that you raised related to the `managed received testimonials` page. 

Is the profile picture now appearing in your `managed received testimonials` page? If so could you please share a screenshot as we don't believe there have been any code changes to this page.

**Comment by CBID2** [comment] 2023-07-02 02:40
Hi @SaraJaoude. To clarify, it's for the managed testimonial section. My use of the word "profile pic" refers to me previously having trouble seeing [!Dean's photo](https://github.com/EddieHubCommunity/LinkFree/assets/105683440/9a450eb5-dc45-4d33-bdb6-3adc8bda25ca) since he wrote the testimonial.

**Comment by SaraJaoude** [comment] 2023-07-02 03:48
> Hi @SaraJaoude. To clarify, it's for the managed testimonial section. My use of the word "profile pic" refers to me previously having trouble seeing 

@CBID2 I think there may be some confusion here.  The second screenshot you added, suggesting the issue could be closed as the profile pic was now appearing was actually a screenshot of your public page (where the profile pic was always appearing). Essentially I suspect you checked the wrong page.  

The enhancement you suggested when creating this issue continues to exist. I shall leave this issue open, but as it is an enhancement which would be "nice to have" I have marked this as `priority: low`.

**Comment by CBID2** [comment] 2023-07-02 03:49
That's fine

**Comment by itsajay1029** [comment] 2023-07-02 09:47
Can you assign this issue to me and explain on what needs to be done ? @Pradumnasaraf

**Comment by eddiejaoude** [comment] 2023-07-02 14:27
@itsajay1029 please do not tag specific maintainers, they all get notified and will respond when they can - please read the contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

I will update the issue description with more information, then you can let us know if you wish to still be assigned the issue

**Comment by Drizer909** [comment] 2023-07-07 11:28
can i get this issue to resolve the problem

**Comment by AJ-KUSHWAH** [comment] 2023-07-07 13:26
I want to contribute on it. Can you please assign it to me.

**Comment by SaraJaoude** [comment] 2023-07-08 06:28
> can i get this issue to resolve the problem

@Drizer909 I have assigned this to you

**Comment by SaraJaoude** [comment] 2023-07-28 08:55
@Drizer909 given there has been no activity for two weeks I have assigned this from you.

**Comment by DaduDev** [comment] 2023-07-30 05:32
Can I solve this?

**Comment by shadow-ryu** [comment] 2023-07-31 11:21
Can I work on this?

**Comment by SaraJaoude** [comment] 2023-08-01 09:35
> Can I solve this?

@DaduDev I have assigned this to you

**Comment by DaduDev** [comment] 2023-08-01 09:47
> > Can I solve this?
> 
> @DaduDev I have assigned this to you

Thank you, let me solve this quickly

**Comment by DaduDev** [comment] 2023-08-01 10:34
I couldn't able to use the project on my local device, I hope I solved the problem, if not just let me know

**Comment by SaraJaoude** [comment] 2023-09-01 08:44
@DaduDev I have unassigned this from you due to lack of activity.

**Comment by sital002** [comment] 2023-09-01 15:15
I would like to work on this issue.

**Comment by SaraJaoude** [comment] 2023-09-02 09:50
> I would like to work on this issue.

@sital002 I have assigned this to you

**Comment by sital002** [comment] 2023-09-03 07:43
just to be clear We need to show the image on the ```account/manage/testimonials``` page 

![Screenshot from 2023-09-03 13-24-45](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/c63e54c9-cd34-4498-992e-1cc0c38acf51)

**Comment by CBID2** [comment] 2023-09-03 16:32
> just to be clear We need to show the image on the ```account/manage/testimonials``` page 
> 
> 
> 
> ![Screenshot from 2023-09-03 13-24-45](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/c63e54c9-cd34-4498-992e-1cc0c38acf51)
> 
> 

Yes @sital002

**Closed** 2023-09-04 06:59 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, good first issue, 🟩 priority: low, 🔢 points: 2, forms
