### ISSUE TITLE
[FEATURE] Add Blogs Section

### ISSUE THREAD

**Issue by amitthecoder** [EddieHubCommunity/BioDrop#8263] opened 2023-07-19 15:11 UTC
### Description

Many developers write technical blogs and want to help beginner developers. If the blog section has been added then beginner developers easily access blogs from pro developers and improve themselves.

**Comment by eddiejaoude** [comment] 2023-07-20 08:13
I like this idea, for people to be able to add content (blog, YouTube, Tweet etc) - I will park this for now as we have a lot going on already

**Comment by SaraJaoude** [comment] 2023-09-30 18:34
Thank you for raising but this is a duplicate of #2274 so I will close this.

**Closed by SaraJaoude** 2023-09-30 18:34 UTC
Labels: ⭐ goal: addition, :thinking: future consideration
