### ISSUE TITLE
[BUG] Pinned links look inactive

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/BioDrop#8046] opened 2023-07-08 06:52 UTC
### Description

Pinned links on the links page look like they are inactive and when I was editing them at a glance I accidentally deleted one of them. If they are set to pinned they could still appear as being active I think.

EDIT: The approach should be to update the style of the pinned tag so that it is bright/active in appearance. Currently it appears dimmed so look inactive.

### Screenshots

![buglinkfree](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/9c0eada8-1822-42db-a59f-a1ce05038b91)

<img width="368" alt="image" src="https://github.com/EddieHubCommunity/LinkFree/assets/19922556/ca1cc04f-4a17-4c50-ba91-17ff40e36487">

![image (4)](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/2bef09ce-f5f6-4b7d-9d3b-5e0c6d670897)

This is a sketch of what it could look like (I'm sure it could be way better).

**Comment by eddiejaoude** [comment] 2023-07-08 07:19
Pinned and disabled are independent, so a link can be disabled from the main link list but still be pinned to the top of your profile

**Comment by harshit-senpai** [comment] 2023-07-08 10:00
hey i would love to work on it

**Comment by eddiejaoude** [comment] 2023-07-08 10:04
> hey i would love to work on it

Please read the contributing guide, from the labels this is not ready for development yet, we are still discussing possible solutions - you can learn more about our labels here https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by amandamartin-dev** [comment] 2023-07-09 19:02
Maybe a solution would be if the link is disabled do not show pinned tag as it's not a relevant tag unless the link is enabled. wdyt?

**Comment by loftwah** [comment] 2023-07-10 00:14
![image](https://github.com/EddieHubCommunity/LinkFree/assets/19922556/8c87120d-630c-4c4a-b892-3dda8c76c0cf)

Anything that makes them not look inactive at a glance should be fine.

**Comment by amandamartin-dev** [comment] 2023-07-11 12:27
> Anything that makes them not look inactive at a glance should be fine.

But if they are disabled, they are inactive? correct?  Or are you saying there is a bug and those pinned links are actually active?

**Comment by loftwah** [comment] 2023-07-11 13:25
Yeah these are the active pinned links. The Disabled badge still shows up (my dodgy sketch tries to explain that but I didn't know how to word it).

**Comment by loftwah** [comment] 2023-07-11 13:27
Uploading chrome_r0pxUnn3Cu.mp4…

I grabbed a quick video to show what I mean.

**Comment by Sahilll15** [comment] 2023-07-17 17:30
I want to work on it

**Comment by eddiejaoude** [comment] 2023-07-17 21:36
The `disabled` only affects the main links list but the link can still be pinned - they are independent. Maybe we need to display this better?

**Comment by eddiejaoude** [comment] 2023-07-17 21:39
> I want to work on it

@Sahilll15 This issue does not have the label `ready for dev` because there is still no solution. Please read the contributing guide, from the labels this is not ready for development yet, we are still discussing possible solutions - you can learn more about our labels here https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md

**Comment by amandamartin-dev** [comment] 2023-07-17 21:56
How about adding a new section above the links called "Socials"

It will be all icons that currently have pinned toggled ON

CLicking on an icon will open the edit for that link

It could live here where i have the red box in the below SS (not bordered like this- just to show the space)

![Socials idea](https://github.com/EddieHubCommunity/LinkFree/assets/97615019/61e7d88d-59ea-4645-b8c1-ac47b7f0757e)

**Comment by loftwah** [comment] 2023-07-18 06:57
I think Eddie is right. Pinned links shouldn't show Enabled or Disabled and they should only show if they are pinned or not pinned.

These could potentially be displayed on the page differently too (as pinned icons rather than the same as a link).

**Comment by eddiejaoude** [comment] 2023-07-18 07:16
Great discussion 👍  thought/challenge, if we displayed them separated, then an enabled link that is also pinned, will be duplicated - but they are the same link in the DB, so any updates would effect both, which could be confusing 🤔

**Comment by eddiejaoude** [comment] 2023-07-18 14:29
> @eddiejaoude That makes sense.
> 
> Perhaps for now we go back to @loftwah original thought is that the main confusion is "pinned" is a dimmed color and therefore looks inactive. So maybe for now a simple style update to make sure the inactive state isn't being applied to the pinned label and we can think on a way to make this more clear in the future?

yes good idea 👍

**Comment by amandamartin-dev** [comment] 2023-07-18 14:33
okay, updated the OP to add the approved approach for htis issue! Maybe the folks helping with your redesign will have an idea for this area too

**Comment by akkshitgupta** [comment] 2023-07-25 09:10
May I get this issue assigned?

**Comment by SaraJaoude** [comment] 2023-07-25 21:02
> May I get this issue assigned?

@akkshitgupta as you were the first to request this once the labels changed, I had assigned this to you.

**Comment by akkshitgupta** [comment] 2023-07-27 11:27
I have fixed the pinned links UI on the profile. If a link disabled then pin icon won't be there on the UI as you can see in the video, i.e, a pin icon would be there only if the link is pinned and enabled as well.

https://github.com/EddieHubCommunity/LinkFree/assets/96991785/3fc9ea13-f94e-45fb-8b03-0056d5b01766

NOTE: I observed that the pinned link is listed on the profile even if it is disabled in this [video](https://github.com/EddieHubCommunity/LinkFree/issues/8046#issuecomment-1630834573). I tried to fix it but I could not reproduce the bug. I am not able to find the origin of `data` object in `UserProfile.js` file.

<details>
<summary>some code from UserProfile.js</summary>
<br>
<img src="https://github.com/EddieHubCommunity/LinkFree/assets/96991785/9a76481d-6fe2-4cec-a37b-02778a06c302" alt="code" />
</details>

**Comment by eddiejaoude** [comment] 2023-07-28 09:00
Thank you @akkshitgupta but this will break many profiles, enabled and pinned are separate, it is how we deal with `links` and `socials` in the json but only use a single url

**Comment by akkshitgupta** [comment] 2023-07-28 09:34
You mean to say the pinned link/socials must be there on the profiles irrespective of the link enabled or disabled? Is it okay to show the pinned icon/tag only if the link is enabled?

**Closed** 2023-08-31 11:10 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 2
