### ISSUE TITLE
[BUG] Icon Alignment Issue in SubNav Bar on Desktop View

### ISSUE THREAD

**Issue by mrical** [EddieHubCommunity/BioDrop#9656] opened 2023-10-29 05:26 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.83.8

### Description

When a new user signs up or goes through the onboarding process, and when accessing the **account panels**, there is an issue with the alignment of icons in the SubNav bar on the desktop view. The icons in the **SubNav bar** are **not** center-aligned as they should be, leading to a **visual inconsistency**.

### Screenshots

<img width="936" alt="dFDbZpG1gh" src="https://github.com/EddieHubCommunity/BioDrop/assets/60258119/dd2a007f-7b41-4182-abac-4923cb06105a">

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

This can be solved by adding a **tailwind CSS** class responsible for center alignment on the button for SubNav,

Here's the result I have obtained on fixing this issue on my **local environment**

<img width="936" alt="chrome_ZRUerPQO3i" src="https://github.com/EddieHubCommunity/BioDrop/assets/60258119/5171b051-74e8-450a-9021-b46eb70b6d05">

**Comment by SaraJaoude** [comment] 2023-10-30 09:31
Thank you for raising - the issue is very well written and this makes such a positive difference to the maintainers.  I have assigned it to you.

**Comment by Luckydhingra** [comment] 2023-10-30 10:23
> Thank you for raising - the issue is very well written and this makes such a positive difference to the maintainers. I have assigned it to you.

- [x] would like to work on this issue
- [x] Participating in Hacktoberfest 23
- [ ] @SaraJaoude Plz assign me

**Comment by sital002** [comment] 2023-10-30 10:29
@Luckydhingra  Please look at the  assignee section before asking for issue to be assigned. I would recommend you to read our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by mrical** [comment] 2023-10-30 13:44
Hello! @SaraJaoude, Thanks for your kind words, I have created a PR #9681 which you can review and merge, you can ask me if there are any doubts regarding my pull request

**Comment by SaraJaoude** [comment] 2023-10-30 19:44
Thank you @mrical  - may I ask that you do not tag a specific maintainer.  All maintainers will receive the notification that the PR has been open, so this is just increasing the notifications.

**Closed** 2023-10-30 19:44 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 2, Hacktoberfest

**Comment by mrical** [comment] 2023-10-30 20:15
@SaraJaoude, I am really sorry about that, It has been 2 years as a developer/freelancer but, this was my first contribution to open source I am not fully aware of every functionality, Thanks to you I gained some experience
