### ISSUE TITLE
[FEATURE] Account/Manage/Link allow editing url of existing link 

### ISSUE THREAD

**Issue by arkohaddoebenezer** [EddieHubCommunity/BioDrop#10243] opened 2024-02-25 17:10 UTC
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I'm honestly not sure if this is a feature or a bug, but I think is more of a feature.
The issue is after creating a link I needed to edit the url and is not allowed.
I can't edit URL of my existing links.
Yet I do not know if it's a premium feature since I use free tier. In that case, this should be considered a bug for not indicating that is a premium feature.
Otherwise mistakes happens and it is good to allow correction other than creating a new link to fix a typo in a url

### Proposed Solution

Enable editing url of existing link

### Screenshots

![Screenshot (88)](https://github.com/EddieHubCommunity/BioDrop/assets/46085267/8ac5869b-4bea-46c4-9bbe-6b385dc3b667)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment] 2024-02-27 08:30
Thank you for raising.  This is not a bug.  If you wish to change the URL you need to create a new link. This has been designed this way to prevent any confusion with the URL statistics. Therefore I will close this issue.

**Closed by SaraJaoude** 2024-02-27 08:30 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
