### ISSUE TITLE
[DOCS] Open Links in Different Tabs

### ISSUE THREAD

**Issue by pritipsingh** [EddieHubCommunity/BioDrop#9029] opened 2023-09-11 23:38 UTC
### Description

This is a very small issue but important for better UX for the future. But when I went to Docs > Quickstart - creating your Profile through Forms

It's asking me to Go to "BioDrop Homepage" with the link embedded to the homepage. Ideally it should open on the different tab on clicking the link, so people can come back and continue following the steps written in the docs by simply switching the tab to create a BioDrop link. Opening in the same page means no going back and bad user experience :)) 

It's a small change but v v v effective for the longer run

### Screenshots

<img width="702" alt="Screenshot 2023-09-12 at 12 31 02 AM" src="https://github.com/EddieHubCommunity/BioDrop/assets/85965351/d9cdb2d5-08ba-4bf6-8beb-1a693448bf5d">

### Do you want to work on this issue?

None

**Comment by SaraJaoude** [comment] 2023-09-14 08:55
Thanks for raising!

**Comment by rizahmeds** [comment] 2023-09-14 10:23
Please assign this issue to me.

**Comment by AbhishekBhure** [comment] 2023-09-14 13:43
I am interested in working on this, can it be assigned to me please?

**Comment by satyam4321** [comment] 2023-09-14 14:22
Can you please assign this issue to me so that i can contribute to 
Looking forward to hear from you guys!

**Comment by SaraJaoude** [comment] 2023-09-15 13:11
@rizahmeds as you were the first to request this once the label changed, I have assigned it to you.

**Comment by sital002** [comment] 2023-09-20 04:30
> Please assign it to me

We are glad that you want to work on this issue but please look on the assignee section if the issue is already assigned look for another issue to work you can find all these information on our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Closed** 2023-09-21 12:24 UTC
Labels: 🏁 status: ready for dev, 🔢 points: 1, 📄 aspect: text
