### ISSUE TITLE
Sort by options on Repo listing page

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/BioDrop#8660] opened 2023-08-15 17:41 UTC
### Description

We can add a filter by options on the repo page that would be helpful for users to sort the repos according to the selected filter

**Comment by amandamartin-dev** [comment] 2023-08-16 12:25
Hello @sumitunique777 I am changing this to a discussion. Please add some details on what the approach would be and what types of options you think would be meaningful to filter on.

**Comment by SaraJaoude** [comment] 2023-08-16 17:21
For now we can start with a simple filter and sort:

Filter by: 

- Stars
- Forks

Sort
- Stars
- Forks

**Comment by ShubhamSj07** [comment] 2023-08-17 14:42
@SaraJaoude do we have any UI design for the filters and sorting?

**Comment by SaraJaoude** [comment] 2023-08-18 09:48
> @SaraJaoude do we have any UI design for the filters and sorting?

@ShubhamSj07 no, but you can reuse existing components.  Here is an example in the Events tab for the dropdown:

<img width="1405" alt="Screenshot 2023-08-18 at 10 46 47" src="https://github.com/EddieHubCommunity/LinkFree/assets/82668196/1caf2c66-8a99-4efc-a78e-157e3cfa5b26">

I will be changing the label for this Issue to `status: ready for dev`.  If you do want to work on this please do not forget to request that this is assigned to you before carrying out any work/opening a PR.

**Comment by ShubhamSj07** [comment] 2023-08-18 10:31
@SaraJaoude Cool!
Please assign it to me, I'd like to give it a try

**Comment by SaraJaoude** [comment] 2023-08-19 08:18
> @SaraJaoude Cool!
> Please assign it to me, I'd like to give it a try

@ShubhamSj07 I have assigned it to you

**Comment by SaraJaoude** [comment] 2023-08-30 19:13
> Since there has been no activity for more than 2 weeks can you assign this to me.
> I would like to work on this issue.

@sital002 I have assigned this to you

**Comment by sital002** [comment] 2023-08-31 03:04
Just to be clear I should only add Filter by:
Stars
Forks
because sort feature is already on another issue https://github.com/EddieHubCommunity/BioDrop/issues/8582

**Comment by eddiejaoude** [comment] 2023-08-31 12:57
@sital002 you are correct, these are duplicates - so I will close this issue and assign the other issue to you - sorry for the confusion

Duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/8582

**Closed by eddiejaoude** 2023-08-31 12:57 UTC
Labels: 🏁 status: ready for dev, 🔢 points: 5
