### ISSUE TITLE
Testimonial delay 

### ISSUE THREAD

**Issue by dhruvabhat24** [EddieHubCommunity/BioDrop#10200] opened 2024-01-31 02:47 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Testimonial Section 

### Version of BioDrop (for example "v1.2.3")

v2.99.11

### Description

Testimonial provide are not fetching to account quickly it will take more than 48 hours. Last week I have received two testimonials among that only one is showing on my dashboard. 

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to <replace your> page.
1. On top right side, close to the <Account> menu
1. Some menu are not working properly.
1. Continue...

If you don't know exact steps, include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Do you want to work on this issue?

No

**Comment by amandamartin-dev** [comment] 2024-02-03 16:05
Hi, you opened this same issue previously and have been in discussion on it with Eddie and other maintainers.  Closing as duplicate.

**Closed by amandamartin-dev** 2024-02-03 16:05 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix

**Comment by eddiejaoude** [comment] 2024-02-04 11:21
Duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/10147
