### ISSUE TITLE
[FEATURE] Profile Delete feature

### ISSUE THREAD

**Issue by amitthecoder** [EddieHubCommunity/BioDrop#8260] opened 2023-07-19 05:32 UTC
### Description

Hello LinkFree Contributors, Today I am creating a LnkeFree account For some reason I want to delete my account but delete option is not available. I removed github authorizations but my profile shows on LinkFree.

**Comment by eddiejaoude** [comment] 2023-07-19 06:58
This was coming soon, but we can make it a higher priority. 

Can I ask why you want to delete your account, not sure what you mean by "some reason"?

**Comment by abhijeetrayy** [comment] 2023-07-19 08:58
I can do that but need your views on it to procced or not (people/geeks)

**Comment by amitthecoder** [comment] 2023-07-19 14:58
Because I am already using link.bio and when I created LinkFree account I
realized the link.bio is better, So I want to delete LinkFree account..

**Comment by eddiejaoude** [comment] 2023-07-20 08:14
> Because I am already using bio.link and when I created LinkFree account I realized the bio.link is better, So I want to delete LinkFree account..
> […](#)

Could you be more specific @amitthecoder , what is better about bio link so we can make improvements? Thanks

**Comment by eddiejaoude** [comment] 2023-07-20 08:18
> I can do that but need your views on it to procced or not (people/geeks)

I suggest adding the delete button to the profile edit page, similar to how we have the delete button for events

DELETE EVENTS BUTTON

<img width="1641" alt="Screenshot 2023-07-20 at 09 15 26" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/4ee4adee-fdeb-4c0d-a875-957498c1854d">

EDIT PROFILE - delete button can go here next to the `save`

<img width="1656" alt="Screenshot 2023-07-20 at 09 15 14" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/8bab1a4a-ac09-4218-99f9-c04aba692273">

Use the same process with the confirmation dialogue...

<img width="1661" alt="Screenshot 2023-07-20 at 09 15 34" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/bb81ada1-50b8-44a5-ab33-0dddcb206e00">

Then on confirmation, change the profile `isEnabled` to `false - we will add a cron later to delete all the data, as we will have lots of stats to delete etc

**Comment by webAbhi** [comment] 2023-07-20 14:04
Hi @eddiejaoude if you don't mind can you assign this issue to me ? this look really interesting, i would love to work on this.

**Comment by yoyoekta** [comment] 2023-07-20 17:00
> <img alt="Screenshot 2023-07-20 at 09 15 34" width="1661" src="https://user-images.githubusercontent.com/624760/254819872-bb81ada1-50b8-44a5-ab33-0dddcb206e00.png">

We can also add confirmation like, the user need to type in the username to permanently delete profile, to add extra layer of safety?

**Comment by vishalsingh2972** [comment] 2023-07-21 15:01
can I work on this if the issue is still open?

**Comment by eddiejaoude** [comment] 2023-07-22 07:39
@webAbhi you asked first, so I have assigned it to you

**Comment by webAbhi** [comment] 2023-07-23 12:48
@eddiejaoude i think `isEnabled` flag is not properly handled in backend, when we send `isEnabled: false` as payload then in response we will receive the value as `true`, which is weird. i am using the same PUT api which is been used for profile data update. even tried replicating the same thing from postman but getting the same result. BTW i have completed the code for this.

**Comment by eddiejaoude** [comment] 2023-07-23 13:16
> @eddiejaoude i think `isEnabled` flag is not properly handled in backend, when we send `isEnabled: false` as payload then in response we will receive the value as `true`, which is weird. i am using the same PUT api which is been used for profile data update. even tried replicating the same thing from postman but getting the same result. BTW i have completed the code for this.

Yes you will need to update the API code for the `PUT` to accept this field  and update it.

Also, if an account is disabled, they will need the functionality to enable it also

**Comment by webAbhi** [comment] 2023-07-23 15:06
> > @eddiejaoude i think `isEnabled` flag is not properly handled in backend, when we send `isEnabled: false` as payload then in response we will receive the value as `true`, which is weird. i am using the same PUT api which is been used for profile data update. even tried replicating the same thing from postman but getting the same result. BTW i have completed the code for this.
> 
> Yes you will need to update the API code for the `PUT` to accept this field and update it.
> 
> Also, if an account is disabled, they will need the functionality to enable it also

So are we looking to make this API update anytime soon or we need to wait for next deployment ? regarding functionality of enabling a disable profile, you can attach the screenshot where you want to see that. i can add that too in same PR.

**Comment by eddiejaoude** [comment] 2023-07-23 15:50
Yes this should be part of this pull request 👍 it does not make sense to be in a separate PR

**Comment by webAbhi** [comment] 2023-07-31 11:24
Hey @eddiejaoude, is there any updates on API ?

**Comment by eddiejaoude** [comment] 2023-07-31 12:22
@webAbhi what do you mean? I thought you were making the required changes in your pull request?

**Comment by webAbhi** [comment] 2023-07-31 12:42
okay my bad, but where are we planning to add a button to enable a disabled profile ?

**Comment by eddiejaoude** [comment] 2023-08-01 09:47
@webAbhi I gave an example in a comment 2 weeks ago here >>> https://github.com/EddieHubCommunity/LinkFree/issues/8260#issuecomment-1643486835

**Comment by SaraJaoude** [comment] 2023-09-25 18:49
Due to lack of activity on https://github.com/EddieHubCommunity/BioDrop/pull/8437 I am unassigning and marking this with a `staff` label as it now has greater priority.

**Comment by shivamsethi** [comment] 2023-10-01 07:08
@eddiejaoude  - I can work on this one. Can you assign this to me?

**Comment by eddiejaoude** [comment] 2023-10-01 07:43
Please don't tag individuals (as mentioned in our contributing guide), other maintainers can assist also. Please see the issue label, it is marked as `staff only`, so only maintainers can work on this issue - you can learn more about our labels in our docs.

**Comment by shivamsethi** [comment] 2023-10-01 07:50
Alright Sure :) Thank you :)

**Comment by eddiejaoude** [comment] 2023-11-22 19:17
Closing as superseded with issue https://github.com/EddieHubCommunity/BioDrop/issues/9821

**Closed by eddiejaoude** 2023-11-22 19:17 UTC
Labels: ⭐ goal: addition, 💻 aspect: code, 🏁 status: ready for dev, 🔢 points: 5, 🔒 staff only
