### ISSUE TITLE
[BUG] Limited Display of Profiles in Search Results

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [EddieHubCommunity/BioDrop#9349] opened 2023-10-04 16:01 UTC
### Description

Edit:
When searching for profiles using tags such as "open source" or "javascript," the `Search` results page only displays 20 profiles on a single page. This results in an unappealing layout with one empty space for a profile card. ~~This issue is consistent across the all project pages~~. Increasing the profile card limit from 20 to 21 would resolve this problem. Please refer to the attached screenshot for visual clarity.

## Top

![Screenshot (43)](https://github.com/EddieHubCommunity/BioDrop/assets/112751524/42c1b8ef-21d7-4945-b1e4-920c2110f75c)

## Bottom

![Screenshot (44)](https://github.com/EddieHubCommunity/BioDrop/assets/112751524/62c53206-2ad2-4380-87c1-4dcbb52421bd)

### Do you want to work on this issue?

Yes

### Additional information

Edit:
Currently this is also reflect on the Discover page, but this page is to be removed as shown here: https://github.com/EddieHubCommunity/BioDrop/issues/9341

By increasing the results (changing from an even number to an odd number), this will fix it for three columns but break it for two columns. However as the two column size is less used, this can be ignored for now (and will be fixed as part of the upcoming redesign).

**Comment by SaraJaoude** [comment] 2023-10-08 11:02
@Shiva-Sai-ssb thank you for raising.  Please see my edits and comments in the Issue description. 

Could you please explain your proposed solution.

**Comment by Shiva-Sai-ssb** [comment] 2023-10-09 12:36
> @Shiva-Sai-ssb thank you for raising. Please see my edits and comments in the Issue description.
> 
> Could you please explain your proposed solution.

I'm new to this project. When I looked at the BioDrop website, I noticed an empty spot where a profile could go. So, I made a request to add a profile there. Yes, if we split it into two columns, there will be even more empty space because the profiles are small. The only way I can think of fixing this is by adding one profile.

**Comment by SaraJaoude** [comment] 2023-10-12 12:41
> > @Shiva-Sai-ssb thank you for raising. Please see my edits and comments in the Issue description.
> > Could you please explain your proposed solution.
> 
> I'm new to this project. When I looked at the BioDrop website, I noticed an empty spot where a profile could go. So, I made a request to add a profile there. Yes, if we split it into two columns, there will be even more empty space because the profiles are small. The only way I can think of fixing this is by adding one profile.

Thank you @Shiva-Sai-ssb  - but by "explain your proposed solution" I meant, what section of code would you change.

Here is the section of the code that needs changing:

https://github.com/EddieHubCommunity/BioDrop/blob/553bed87c1023c8be8f76b8e11de7d934bc96854/pages/search.js#L198

I will assign this issue to you.

**Comment by Abhishek9503** [comment] 2023-10-13 06:15
> The issue has been unlocked and is now ready for dev. If you would like to work on this issue, you can comment to have it assigned to you. You can learn more in our contributing guide https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

I want to work on this issue please assign me this issue .I hope i could start my first contribution to the community by solving this issue.

**Comment by Shiva-Sai-ssb** [comment] 2023-10-13 06:52
> > The issue has been unlocked and is now ready for dev. If you would like to work on this issue, you can comment to have it assigned to you. You can learn more in our contributing guide https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md
> 
> I want to work on this issue please assign me this issue .I hope i could start my first contribution to the community by solving this issue.

Hi, I've opened this issue and said that I'm ready to work on it. It's my first time contributing to this project, and I'll submit a pull request for it soon. Can you please check out a other issues?

**Comment by eddiejaoude** [comment] 2023-10-13 10:26
Don't worry @Shiva-Sai-ssb, the issue is assigned to you and I am going to review your PR now

**Closed** 2023-10-13 10:27 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, good first issue, 🔢 points: 1, Hacktoberfest
