### ISSUE TITLE
[BUG] Low contrast update on account page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9294] opened 2023-10-03 13:55 UTC
### Description

On this url, there is a section offering hints to complete your profile. [Account onboarding url](https://www.biodrop.io/account/onboarding)

In dark mode, please update the text to be displayed in white (consistent with other dark mode white text)

See screenshot for location of text.

### Screenshots

![low-contrast](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/8f04a964-04ca-4639-9bcb-187b0171e561)

### Do you want to work on this issue?

None

**Comment by sricharanandra** [comment] 2023-10-03 14:00
@amandamartin-dev  I can take this up!

**Comment by ATREAY** [comment] 2023-10-03 14:00
hey @amandamartin-dev, can I work on this issue?

**Comment by SaraJaoude** [comment] 2023-10-03 14:44
> amandamartin-dev I can take this up!

@sricharanandra as you were the first to request I have assigned this to you. In future please avoid tagging a specific maintainer - all maintainers receive notifications and can assign issues.

**Comment by ATREAY** [comment] 2023-10-09 09:48
Is this issue still open? The PR hasn't been merged yet, and the contributor is experiencing some issues. I was wondering if I could give it a try.

**Comment by SaraJaoude** [comment] 2023-10-09 17:56
> Is this issue still open? The PR hasn't been merged yet, and the contributor is experiencing some issues. I was wondering if I could give it a try.

@ATREAY the issue is still open but is still assigned to someone else.  We encourage collaboration so it would be more helpful if you could provide some support to the assignee with the challenges they are facing.

**Closed** 2023-10-17 10:05 UTC
Labels: 🛠 goal: fix, good first issue, 🔢 points: 1, Hacktoberfest
