### ISSUE TITLE
[BUG] Secondary Navbar Overflow Issue Between 630px to 740px Screen Width

### ISSUE THREAD

**Issue by Keshav-0907** [EddieHubCommunity/BioDrop#9891] opened 2023-12-10 21:20 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

biodrop.io

### Version of BioDrop (for example "v1.2.3")

v2.95.0

### Description

When the screen width is between `630px` to `740px`, the contents of the secondary menu/navbar exceeds the available space, causing overflow issues.

(Refer to attached Screenshot)

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to `https://www.biodrop.io/account/onboarding` page.
2. Make the screen width with b/w `630px` to `740px`

### Screenshots

<img width="391" alt="Screenshot 2023-12-11 at 2 36 29 AM" src="https://github.com/EddieHubCommunity/BioDrop/assets/91189139/43aae0b3-50a1-461d-9660-3535b912dba2">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

There are multiple ways to fix this issue:

Implementing an overflow hidden property and allowing horizontal scrolling.
or
Displaying the horizontal menu in two rows specifically for this resolution.

**Comment by ankittankal** [comment] 2023-12-17 10:02
@SaraJaoude  For example : IPad Mini( 768 * 1024)
![Screenshot_20231217_152948](https://github.com/EddieHubCommunity/BioDrop/assets/68264331/295ed41f-f350-4634-b344-08b8d176e93d)

**Comment by ankittankal** [comment] 2023-12-17 13:23
@SaraJaoude  I would like to work on this

**Comment by SaraJaoude** [comment] 2023-12-20 09:38
@ankittankal whilst we appreciate your enthusiasm please follow the Contributing Guide and do not tag a specific maintainer (especially twice on the same day) unless it is very urgent.  Please respect that maintainers have other duties and commitments beyond this project and cannot always respond immediately. 

All maintainers receive notifications and can deal with issues. 

I will assign this to you.

I would suggest changing to the mobile dropdown version of the nav at a larger resolution where the current nav starts to overflow.

**Comment by ankittankal** [comment] 2023-12-21 04:32
Thank you for the feedback and for assigning the task to me. I apologize for any inconvenience caused by my actions. I acknowledge the importance of following the Contributing Guide and respecting the time commitments of maintainers. I will ensure to adhere to the guidelines moving forward. I'll promptly work on implementing the suggested change to the mobile dropdown version of the navigation. If there are any additional details or tasks you'd like me to prioritize, please let me know. I'm here to help and contribute positively to the project.

**Comment by OussBenO** [comment] 2024-01-07 21:45
Hi @Keshav-0907 

I hope this message finds you well. I wanted to check in on the status of Issue #9891 related to the secondary navbar overflow problem between 630px to 740px screen width. I noticed that ankittankal was assigned to address the issue, and I'm curious about the progress or any updates on the resolution.

Your efforts are greatly appreciated, and I understand that these matters take time. If there are any challenges or additional information needed, please feel free to let me know.

**Comment by ankittankal** [comment] 2024-01-08 05:21
I hope this message finds you well too! Thank you for checking in on the
status of Issue #9891 regarding the secondary navbar overflow issue.

I wanted to inform you that I have already addressed this concern by
submitting a Pull Request (PR) two weeks ago. The changes aimed at
resolving the problem occurring between 630px to 740px screen widths have
been included in the PR. You can review the PR at the following link:  [PR
Link](https://github.com/EddieHubCommunity/BioDrop/pull/10023)

Please take a moment to review the PR at your earliest convenience. If
there are any additional details needed or further steps required from my
end, please feel free to let me know.

Thank you for your support and understanding.

Best regards,

Ankit

**Comment by OussBenO** [comment] 2024-01-08 13:30
Hi  @ankittankal 

 Your detailed information is helpful. I'll review the PR soon and get back to you.

**Closed** 2024-01-21 08:45 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 3
