### ISSUE TITLE
[FEATURE] Open Issue count badge on repo page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9297] opened 2023-10-03 14:11 UTC
### Description

This issue is to add a new badge on the repo pages to show if a repo has any open issues. This will help contributors discover new repositories to contribute to.

https://www.biodrop.io/repos

### Screenshots

Screenshot of location of new badge.  Color and icon can be chosen by the developer - can discuss if needed

![new-badge-location](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/91cb4f5c-ada5-4e55-a70f-9386257d8a75)

### Do you want to work on this issue?

No

**Comment by MeenuyD** [comment] 2023-10-03 14:14
can I work on this issue

**Comment by PradeepG-07** [comment] 2023-10-03 14:24
please assign me this issue

**Comment by SaraJaoude** [comment] 2023-10-03 14:46
> can I work on this issue

@MeenuyD I have already assigned an issue to you.  As mentioned in our [Contributing Guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) we only assign one issue per person.  Please also avoid commenting on multiple issues until you are assigned something - this creates a lot of unnecessary noise and notifications.

**Comment by SaraJaoude** [comment] 2023-10-03 14:47
> please assign me this issue

@PradeepG-07  I have assigned this to you.

**Comment by PradeepG-07** [comment] 2023-10-03 17:35
Hello @SaraJaoude  according to my knowledge the repo.js file don't have any related information about issues. I need to make a api get request to know if there are any open issues available on that repo. But the problem is I don't have accesskey to make a api request. Could please help me?

**Comment by PradeepG-07** [comment] 2023-10-03 18:52
Hello @SaraJaoude I have a doubt regarding the adding of icon for issues i.e. the folder which contains the icons is not available in your repo. 

<img width="928" alt="Screenshot 2023-10-04 001738" src="https://github.com/EddieHubCommunity/BioDrop/assets/143615010/3d2e300a-32b3-4785-8f89-f24b75082492">

Unable to find "@heroicons/react/20/solid/"

**Comment by SaraJaoude** [comment] 2023-10-03 20:06
@PradeepG-07 this comes in as an npm dependency so won't be in our file structure.

**Comment by PradeepG-07** [comment] 2023-10-04 01:48
Hey @SaraJaoude I have made a PR please verify it and i am very thankful to you and your community for letting me work in BioBrop.
Thank You.

**Closed** 2023-10-04 07:32 UTC
Labels: ⭐ goal: addition, good first issue, 🔢 points: 2, Hacktoberfest
