### ISSUE TITLE
[BUG] The Navbar isn't fixed to the top of my screen.

### ISSUE THREAD

**Issue by hi-Kartik2004** [EddieHubCommunity/BioDrop#9271] opened 2023-10-02 18:22 UTC
### Description

The navbar isn't fixed to the top of my screen and I lose my navigatin links as soon as I scroll the page, and have to scroll all the way to the top to navigation to other sections of the website.

Hence I a fixed navigation bar (Navbar) is suggested.

### Do you want to work on this issue?

No

### Additional information

You can easily replicate this issue on any route at https://biodrop.io

**Comment by SaraJaoude** [comment] 2023-10-03 09:41
Thank you for raising. But this is not a bug, it is designed this way. Many websites have adopted this design choice - for example, the GitHub website.  I am therefore closing this.

**Closed by SaraJaoude** 2023-10-03 09:41 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
