### ISSUE TITLE
[FEATURE] Use search engine for Search

### ISSUE THREAD

**Issue by developer-diganta** [EddieHubCommunity/BioDrop#900] opened 2022-01-03 07:51 UTC
### What would you like to share?

I was thinking if we can implement [FuseJs](https://fusejs.io/) for search?

**Comment by emmalearnscode** [comment] 2022-01-03 10:59
Can you explain a bit more about it and how it could benefit the project

**Comment by developer-diganta** [comment] 2022-01-04 18:24
@emmalearnscode I am not sure if this will be of some huge help but I thinkFuseJs can help get close search results. For example, if someone's name is Jenny and someone types just Jeny then FuseJs can list out the name (it does it on the closeness of the word entered by the user).

**Comment by ManishBisht777** [comment] 2023-01-24 19:20
i want to work on this

**Comment by SaraJaoude** [comment] 2023-09-30 17:11
Closing as this is a duplicate of #8169

**Closed by SaraJaoude** 2023-09-30 17:11 UTC
Labels: ⭐ goal: addition, :thinking: future consideration
