### ISSUE TITLE
Search Page: Fix Badges Overlapping Issue with Text

### ISSUE THREAD

**Issue by guptadeepak8** [EddieHubCommunity/BioDrop#9828] opened 2023-11-24 12:03 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.90.1

### Description

Badges at the top, representing numbers, are overlapping affecting their appearance. Look at the options with numbers on top. To fix it, we need to adjust how these badges are positioned.

### Steps to Reproduce

1. Navigate to the search navbar.
2. Look for options with badges representing numbers at the top.
3. Observe the overlap issue

### Screenshots

![Screenshot (668)](https://github.com/EddieHubCommunity/BioDrop/assets/91896859/68144b61-b40c-49de-90b0-0896ad2b4ac7)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment] 2023-11-27 07:43
>  I have checked "open" AND "closed" issues and this is not a duplicate

Thank you for raising, but this is a duplicate of (just some examples)...
- https://github.com/EddieHubCommunity/BioDrop/issues/9658
- https://github.com/EddieHubCommunity/BioDrop/issues/9066
- https://github.com/EddieHubCommunity/BioDrop/issues/5828
- ...

**Closed by eddiejaoude** 2023-11-27 07:43 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
