### ISSUE TITLE
[BUG] Speaking at event not displayed

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/BioDrop#9190] opened 2023-09-28 08:08 UTC
### Description

On the events manage page the info is shown...

<img width="1669" alt="Screenshot 2023-09-28 at 09 05 33" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/e2d95112-c13d-4f80-a1c0-64e33fdafd0a">

But on the main events page it is not displayed...

<img width="1672" alt="Screenshot 2023-09-28 at 09 05 24" src="https://github.com/EddieHubCommunity/BioDrop/assets/624760/50008765-68c2-432c-9e25-e42bc6521882">

### Do you want to work on this issue?

None

**Comment by sanketmp** [comment] 2023-09-28 08:23
can I do this?

**Comment by Dun-sin** [comment] 2023-09-28 08:47
can i take this?

**Comment by AbhijeetBiswal** [comment] 2023-09-28 08:49
can you please assign me this issue

**Comment by amandamartin-dev** [comment] 2023-09-28 12:54
> can i take this?

Yes, I will assign you now. Thanks for contributing!

**Comment by amandamartin-dev** [comment] 2023-09-28 12:56
@eddiejaoude I have assigned this issue to someone as it was unlocked, but I thought this was by design bc of the 1:many nature of the community events page?

I believe this was discussed somewhere else that it only makes sense to list speaking on personal pages due to this issue, but please advise if I am misremembering.

**Comment by eddiejaoude** [comment] 2023-09-28 13:11
Oh good point Amanda 😱 yes we don't know which to display if there are multiple people attending the same event. 

I will close this issue, sorry for the confusion

**Closed** 2023-09-28 13:11 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🛠 goal: fix, good first issue, 🔢 points: 2
