### ISSUE TITLE
[BUG] tags accepting duplicate values and removing tag is not proper

### ISSUE THREAD

**Issue by JeevaRamanathan** [EddieHubCommunity/BioDrop#9706] opened 2023-10-31 15:25 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

https://www.biodrop.io/account/manage/profile

### Version of BioDrop (for example "v1.2.3")

v2.83.18

### Description

Currently the tags section is accepting same inputs more than once, but on removing either by backspace or x mark, instead of removing only the particular tag, it's removing all the occurrence of that word at once. This happens both in profile and events page.

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/64531160/f2e06e9e-3f53-4c04-942a-7db6b14f601d)

### Do you want to work on this issue?

Yes

### If you want to work on this issue...

Hoping that the functionality should be like the tags should be unique, I would like to approach this in a way where if user types the same word and after pressing comma the input box should reset by removing that value (something like in medium.com tags)

https://github.com/EddieHubCommunity/BioDrop/assets/64531160/a36c467c-f3eb-4c80-99fa-37200ac0d041

Kindly check and suggest if that would work or is it required to be accept same tags twice by removing particular tag or in any other way.

**Comment by amandamartin-dev** [comment] 2023-11-10 20:30
Confirmed this bug is happening and thank you for providing your approach, however in the video you provided the user gets no feedback on why they cannot add the duplicate tag. I would propose also making sure that it is clear why the attempted duplicate disappeared and provide clear instructions in the documentation that duplicate tags are not accepted.

**Comment by SaraJaoude** [comment] 2023-11-21 09:54
@JeevaRamanathan as it has been two weeks since this was assigned to you and there has been no activity, I am unassigning this issue from you, so that someone else can have the opportunity to contribute.

**Comment by badrivlog** [comment] 2023-11-21 10:29
Please assign me

**Comment by SaraJaoude** [comment] 2023-11-21 16:27
> Please assign me

@badrivlog I have assigned this to you

**Closed** 2023-11-23 14:27 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, 🔢 points: 3
