### ISSUE TITLE
[FEATURE] Add Steps to Reproduce in Bug 🐛 Issue template

### ISSUE THREAD

**Issue by Kamaruddheen** [EddieHubCommunity/BioDrop#9742] opened 2023-11-07 18:10 UTC
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently there is no standardized way to provide steps to reproduce a bug or issue within GitHub issue templates. This makes it difficult/extra work for maintainers and contributors to reproduce reported issues after creating an issue. A "Steps to Reproduce" section would solve this problem. We can bring awareness to providing steps to reproduce when creating an issue itself.

### Proposed Solution

Adding a new optional section of "Steps to Reproduce" in issue template of Bug 🐛. This section would allow the user to provide a steps to reproduce the bug or issue in numbered list. 

#### Steps to Reproduce

1. 
2.
3.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

To implement this, the Issue Template of `bug.yml` would need to be updated to support adding a new section called **Steps to Reproduce**

- Adding a new field definition in the YML file for `stepsToReproduce` as a `textarea` type.
- Using the `placeholder` property to provide a sample format such as:

```
1. First step...
2. Second step..
3. etc.
```
- The `required` property could be set to `true` since having steps to reproduce is important for maintainer.

**Comment by amandamartin-dev** [comment] 2023-11-10 20:19
I love this idea.  I think making it required is ideal, but sometimes folks don't know exactly how to reproduce a bug.

Maybe a step first saying "Do you know how to reproduce this bug" if they select yes, steps are required

wdyt?

I will unlock and assign to you as well

**Comment by eddiejaoude** [comment] 2023-11-11 07:26
> Maybe a step first saying "Do you know how to reproduce this bug" if they select yes, steps are required

I think most will always select "no" because it is less work. What about making it required and seeing how it goes - if people don't know they will write something just to progress, we see that in other require fields for features template but it definitely had an overall positive impact

**Comment by Kamaruddheen** [comment] 2023-11-11 08:38
> I love this idea. I think making it required is ideal, but sometimes folks don't know exactly how to reproduce a bug.
> 
> Maybe a step first saying "Do you know how to reproduce this bug" if they select yes, steps are required
> 
> wdyt?
> 
> I will unlock and assign to you as well

It could work out, but I personally think from maintainers perspective it is extract work for us to do. If It's required, even if the steps aren't perfect, some info is better than nothing. This will reduce the burden on us to find out bugs from scratch and make our lives much easier.

Also, I have seen in some issue for "Do you want to work on this issue?" as empty, Not even "Yes or No"
Could it be because required is set to false?

**Comment by Kamaruddheen** [comment] 2023-11-11 08:40
> > Maybe a step first saying "Do you know how to reproduce this bug" if they select yes, steps are required
> 
> I think most will always select "no" because it is less work. What about making it required and seeing how it goes - if people don't know they will write something just to progress, we see that in other require fields for features template but it definitely had an overall positive impact

Making it required could work out if we follow below, 
- People who knows the steps can provide it. (they can follow placeholder template or prefilled value)
- People who knows it partially can give heads up steps for us
- People who doesn't have any idea, we can allow them to enter "Could not reproduce", "Need help", etc.. 

We can mention these with in placeholder of input field along with the steps. Let me know what you think?

**Closed** 2023-11-17 18:41 UTC
Labels: ⭐ goal: addition, 🏁 status: ready for dev
