### ISSUE TITLE
[FEATURE] Improvement - link help to FAQ page

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9291] opened 2023-10-03 13:37 UTC
### Description

This update is to change the url for the floating help button to point to the FAQ page.  Currently it points to github discussions which is unexpected when searching for help.

[FAQ page](https://www.biodrop.io/docs/faqs)

Screenshot showing Help button location
![help-arrow](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/116c9b3f-f448-4a54-a26a-983764942886)

### Do you want to work on this issue?

No

**Comment by AbhijeetBiswal** [comment] 2023-10-03 13:40
can you please assign me this issue

**Comment by MeenuyD** [comment] 2023-10-03 13:40
can you please assign it to me

**Comment by hemanth110702** [comment] 2023-10-03 13:43
Hey, I would like to work on this. Can you please assign this to me?

**Comment by a-s-t-e-y-a** [comment] 2023-10-03 13:58
@amandamartin-dev, I have generated the PR. Kindly review the PR. If it meets your requirements, please merge it; otherwise, please state the reason.

**Comment by SaraJaoude** [comment] 2023-10-03 14:33
> can you please assign me this issue

@AbhijeetBiswal I have assigned this to you.

**Comment by a-s-t-e-y-a** [comment] 2023-10-03 14:33
@SaraJaoude can you assign me to another issue

**Comment by SaraJaoude** [comment] 2023-10-03 14:42
> @SaraJaoude can you assign me to another issue

@a-s-t-e-y-a as suggested already please read the Contributing Guide. You need to check what issues have the label `status: ready for dev`, check that they have not been unassigned to anyone else and then request that the issue is assigned to you (without tagging a specific maintainer).

**Closed** 2023-10-07 05:15 UTC
Labels: ⭐ goal: addition, good first issue, 🔢 points: 1, Hacktoberfest
