### ISSUE TITLE
[BUG] Update old screenshot

### ISSUE THREAD

**Issue by mehra-sourav** [EddieHubCommunity/BioDrop#9446] opened 2023-10-10 13:01 UTC
### Description

The BioDrop map screenshot in the BioDrop homepage is still using the old LinkFree screenshot.

Link: https://www.biodrop.io/#:~:text=this%20page%20also.-,BioDrop%20Map,-Discover%20people%20around

### Do you want to work on this issue?

Yes

### Additional information

This is probably a decent 'good first issue'.

**Comment by eddiejaoude** [comment] 2023-10-15 04:55
Thank you for raising, this is a duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/8814, so I will close.

**Closed by eddiejaoude** 2023-10-15 04:55 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
