### ISSUE TITLE
[FEATURE] QuickStart Screenshots

### ISSUE THREAD

**Issue by rahulpandey70** [EddieHubCommunity/BioDrop#9418] opened 2023-10-08 20:04 UTC
### Description

We are still using old `LinkFree UI` screenshot.

reference:- https://www.biodrop.io/docs/quickstart-forms

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment] 2023-10-15 04:55
Thank you for raising, this is a duplicate of https://github.com/EddieHubCommunity/BioDrop/issues/8814, so I will close.

**Closed by eddiejaoude** 2023-10-15 04:55 UTC
Labels: ⭐ goal: addition, 🚦 status: awaiting triage
