### ISSUE TITLE
[BUG] background visible 

### ISSUE THREAD

**Issue by oyepriyansh** [EddieHubCommunity/BioDrop#9461] opened 2023-10-11 17:58 UTC
### Description

In glow mode, the background is visible in the links.
You can check on my profile.
https://www.biodrop.io/oyepriyansh

### Screenshots

![IMG_3677](https://github.com/EddieHubCommunity/BioDrop/assets/83062406/be2ef5b0-3b4a-4823-9275-c996505f5a17)

### Do you want to work on this issue?

No

**Comment by micahyoung324** [comment] 2023-10-12 12:28
I can give this a shot. Thanks!

**Comment by Abhishek-90** [comment] 2023-10-12 14:12
I would like to take it up. Thankyou!

**Comment by Tanush-J** [comment] 2023-10-12 15:48
I am not able to reproduce the issue, can you give steps to reproduce

<img width="230" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/75922615/4950cb17-24c3-4fb0-b13d-c738739e7f3d">

**Comment by imshivamrai282** [comment] 2023-10-12 19:35
Hey! @oyepriyansh I can give it a try.

**Comment by oyepriyansh** [comment] 2023-10-13 03:41
> Hey! @oyepriyansh I can give it a try.

I am not the maintainer of this repository. You can just leave a comment here, and a maintainer may assign the task to you

**Comment by mianakbarjan** [comment] 2023-10-13 07:14
Hey @oyepriyansh, can you give more details on the issue since everything looks fine when I open your site

**Comment by Karan-Palan** [comment] 2023-10-13 07:55
@oyepriyansh , 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/143683619/42266957-22b1-4c2b-a270-c54eb52fd3e7)
Everything looks fine when i open your site! Please provide more details

**Comment by mehra-sourav** [comment] 2023-10-13 12:27
Could you provide the steps to reproduce the bug @oyepriyansh ? It seems like a lot of devs can't seem to replicate the bug, including me.

**Comment by mozi47** [comment] 2023-10-13 17:34
Tried it on Firefox, Edge, and Chrome but this looks fine to me.

**Comment by Shauryagulati** [comment] 2023-10-14 12:42
Tried it on Safari Browser. The issue persists. 
![Screenshot 2023-10-14 at 6 11 49 PM](https://github.com/EddieHubCommunity/BioDrop/assets/41816749/c93c00b5-0182-48ed-87d8-c9db0503a33e)

**Comment by YuriDevAT** [comment] 2023-10-21 15:33
I could reproduce the issue (Safari). It seems like there is a `rounded-full` value missing on the parent `div` of the `a`. I would be happy to work on this issues 🙂

**Comment by SaraJaoude** [comment] 2023-10-22 09:47
> I could reproduce the issue (Safari). It seems like there is a `rounded-full` value missing on the parent `div` of the `a`. I would be happy to work on this issues 🙂

Thanks @YuriDevAT ! I have assigned this to you.

**Comment by YuriDevAT** [comment] 2023-10-28 16:55
### Conclusion
❗After thoroughly researching the topic, I came to the conclusion that either

1. reduce the effect in general or
2. leave it and hope for Safari Browser support in the future.

### Why? My findings
[Safari does not support Animation on selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/::after) like `::before` or `::after`. When removing (or reducing) the animation, in this particular case it is the `background-size` on `::after` which should be reduced to 100%, removes the buggy background, which is only a problem in Safari. Therefore it would make sense to get somehow the information if the user is currently in a Safari browser. I tried to use `userAgent` as well as `@support` but both did not work.
**Result:** The animation effect is not that intense anymore.

Example of `@support`
```
@supports
selector(:nth-child(1 of x)) {
...
}
```

### More details:
I created [an article on dev.to](https://dev.to/yuridevat/how-support-works-4bf3) to explain in detail, share code and screenshots, and get help from other developers who are more experienced with CSS Animation. 

### Pull Request
Please let me know how I should proceed with this issue

1. If I should wait for someone who comes up with a better support rule which works for sure (but even those can be outdated soon),
2. if I should reduce the background-size in general, or
3. if I should leave it as it is (I guess, the issue gets closed, no PR needed)

**Comment by eddiejaoude** [comment] 2023-10-31 11:43
Thank you @YuriDevAT for the detailed research 🚀  

Can we see what it looks like using option 2 "the reduced background size"?

**Comment by YuriDevAT** [comment] 2023-11-03 14:17
Please find the link to my codepen, which has currently the reduced background size.

https://codepen.io/YuriDevAT/pen/NWoPwpx

If you comment out line 61, you can see the difference. By setting the size down to 100%, the effect is almost only on the ::before and not that that WOW anymore.

**Comment by mahesh-s33** [comment] 2023-11-08 19:55
I would like to take it up. Thankyou!

**Comment by eddiejaoude** [comment] 2023-11-08 22:22
> Please find the link to my codepen, which has currently the reduced `background size`.
> 
> https://codepen.io/YuriDevAT/pen/NWoPwpx
> 
> If you comment out `line 61`, you can see the difference. By setting the size down to `100%`, the effect is almost only on the `::before` and not that that WOW 👀 anymore.

it looks great @YuriDevAT 👍

**Comment by eddiejaoude** [comment] 2023-11-08 22:23
> I would like to take it up. Thankyou!

@mahesh-s33 this issue is already assigned, please check the assignee section in the issue first

**Comment by mahesh-s33** [comment] 2023-11-08 22:40
> > I would like to take it up. Thankyou!
> 
> @mahesh-s33 this issue is already assigned, please check the assignee section in the issue first

Sure i'll collaborate once the PR is raised.

**Closed** 2023-11-12 18:43 UTC
Labels: 🏁 status: ready for dev, 🛠 goal: fix, Hacktoberfest
