### ISSUE TITLE
[DOCS] pages/docs/environments/linkfree-cli.mdx should be changed to BioDrop as well

### ISSUE THREAD

**Issue by sanyamx** [EddieHubCommunity/BioDrop#8845] opened 2023-08-29 11:59 UTC
### Description

linkfree-cli still follows the name which should now follow the name of BioDrop
the path to the file is pages/docs/environments/linkfree-cli.mdx

**Comment by SaraJaoude** [comment] 2023-08-31 10:46
Thank you for raising!

**Comment by sanyamx** [comment] 2023-08-31 11:36
I would like to work on the issue!

**Comment by SaraJaoude** [comment] 2023-08-31 12:49
> I would like to work on the issue!

@sanyamx I have assigned this to you. In future if you would like to work on an Issue that you have created (and do not currently have anything assigned to you) then please do mention this in the `Additional Information` section and one of the maintainers can assign this immediately, if the Issue is marked as ready.

**Comment by sanyamx** [comment] 2023-08-31 15:32
> 

Thank you for the assignment! I will keep sure to mention about assignment while creating an issue!

**Comment by sanyamx** [comment] 2023-09-02 07:29
I want to ask a question regarding the issue.
Question - In future do you plan to change the name of CLI tool as well? if yes, then I would update the changes in the file accordingly (it would be wise to change the name of CLI tool as well). Except that I have made the appropriate changes to the file which are attached to the PR below.

**Comment by eddiejaoude** [comment] 2023-09-04 06:54
Thanks @sanyamx you would have to raise an issue on the cli project to request it to be renamed

**Comment by Pradumnasaraf** [comment] 2023-09-04 16:45
Hey,

This issue should be currently on hold. I am looking into changing the CLI package (Sadly, not easy, because there is no way to rename 😞 ) 

So, 1st the CLI will get a rename the docs will proceed (Hopefully soon). Also, I will be self-assigning this issue to make this change.

**Comment by SaraJaoude** [comment] 2023-09-07 19:53
> Hey,
> 
> This issue should be currently on hold. I am looking into changing the CLI package (Sadly, not easy, because there is no way to rename 😞 )
> 
> So, 1st the CLI will get a rename, then the docs will proceed (Hopefully soon). Also, I will be self-assigning this issue to make this change.

Thanks @Pradumnasaraf  - in that case I will block the issue and also assign this to you.

**Closed** 2023-09-11 10:16 UTC
Labels: 🏁 status: ready for dev, 🔢 points: 2, 📄 aspect: text
