### ISSUE TITLE
[BUG] <Unnecessary number displayed bottom of the profile view box>

### ISSUE THREAD

**Issue by Aishvarya0510** [EddieHubCommunity/BioDrop#8742] opened 2023-08-22 19:25 UTC
### Description

After signing up [http://linkfree.io](https://t.co/o5elu39Oxy)
I saw a number printed on the bottom of the view profile box.

### Screenshots

![image](https://github.com/EddieHubCommunity/LinkFree/assets/74362776/26669656-7b31-4c79-91e6-a31a0016c986)

**Comment by amandamartin-dev** [comment] 2023-08-23 12:27
I am guessing this is happening because this is a new profile with no statistics yet.  I am unable to confirm though and not sure the best way to test

My profile for example
![profile](https://github.com/EddieHubCommunity/LinkFree/assets/97615019/37a44f9a-d29a-4ff6-ae2c-ec09be46cb9b)

**Comment by eddiejaoude** [comment] 2023-08-28 09:11
Thank you for raising 👍 

I think it is a duplicate of issue https://github.com/EddieHubCommunity/BioDrop/issues/8684, so I will close

**Closed by eddiejaoude** 2023-08-28 09:11 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
