### ISSUE TITLE
Improvement:Add button on repo listing page

### ISSUE THREAD

**Issue by sumitunique777** [EddieHubCommunity/BioDrop#9659] opened 2023-10-29 06:55 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of BioDrop (for example "v1.2.3")

v2.83.8

### Description

We can place a add repo button here on repo listing page as well.

### Screenshots

![Uploading image.png…]()

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment] 2023-10-30 09:36
The image did not upload so we are unsure what this issue is about.  Please can you update the issue description for this to be considered by the maintainers. 

Also, I can see that you want to work on this issue - please complete the section `If you want to work on this issue` with your proposed solution.

**Comment by kundan766** [comment] 2023-10-31 15:25
can you assign me the issue .i want to work on this issue

**Comment by sital002** [comment] 2023-11-01 05:56
> can you assign me the issue .i want to work on this issue

This issue  isnot labeled ```status:ready for dev``` @kundan766  please read our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md

**Comment by eddiejaoude** [comment] 2023-11-01 08:27
@kundan766 not sure how you could work on it, it is not clear what the issue is about. Please see Sital's comment.

To avoid further confusion I am closing this issue.

**Closed by eddiejaoude** 2023-11-01 08:27 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
