### ISSUE TITLE
[IMPROVEMENT] search api full-text-search

### ISSUE THREAD

**Issue by badrivlog** [EddieHubCommunity/BioDrop#8169] opened 2023-07-13 06:55 UTC
### What would you like to share?

Currently, we have been filter users by JavaScript, that's not efficient for performance. Instead it would be better to perform that logic by MongoDB full-text-search.

**Comment by eddiejaoude** [comment] 2023-07-14 10:52
This would be a great improvement 👍

**Comment by ArnabChatterjee20k** [comment] 2023-07-14 11:05
Can I work on it

**Comment by SaraJaoude** [comment] 2023-07-15 07:52
> Can I work on it

@ArnabChatterjee20k I have assigned this to you

**Comment by ArnabChatterjee20k** [comment] 2023-07-23 07:15
One question I have, full text search wont search for substrings in the slug. So we have to enter the full name to get the results.
So will it be be good to implement this?

**Comment by eddiejaoude** [comment] 2023-07-23 07:42
Can you five an example of what you mean? But if I think I understand, partial search keyword match should return results

**Comment by ArnabChatterjee20k** [comment] 2023-07-23 07:55
**Full text search example**
My name - ArnabChatterjee20k
Now if I search for Arnab or arnab , it will not return results
I have to search for ArnabChatterjee20k to get the result

Partial searching or pattern searching will give the result by getting the pattern

But the issue is asking for full text search.
So I asked this question

**Comment by ArnabChatterjee20k** [comment] 2023-07-23 07:55
> Can you five an example of what you mean? But if I think I understand, partial search keyword match should return results

Yes partial or pattern searching is the ideal one here

**Comment by eddiejaoude** [comment] 2023-07-23 08:08
Yes fulltext search is designed for partial matches, similar to google search, here from the mongo docs...

> Full-text search refers to searching some text inside extensive text data stored electronically and returning results that contain some or all of the words from the query. In contrast, traditional search would return exact matches.

https://www.mongodb.com/basics/full-text-search

**Comment by ArnabChatterjee20k** [comment] 2023-07-27 00:15
I am currently facing this issue and not getting any solution. I am trying it from the last 2days. 
Here is solution and the approch and exactly what issue is coming
https://stackoverflow.com/questions/76773218/constructing-a-mongodb-query-to-emulate-javascript-filtering-logic-filterevery?noredirect=1#comment135348552_76773218

**Comment by eddiejaoude** [comment] 2023-07-28 12:35
> I am currently facing this issue and not getting any solution. I am trying it from the last 2days.
> Here is solution and the approch and exactly what issue is coming
> https://stackoverflow.com/questions/76773218/constructing-a-mongodb-query-to-emulate-javascript-filtering-logic-filterevery?noredirect=1#comment135348552_76773218

I think trying to replicate javascript is not the correct approach, mongo has full text search which we should move to, here is an official example from their docs with features like scoring, fuzzy search etc https://www.mongodb.com/developer/products/atlas/build-movie-search-application/

**Comment by jackli921** [comment] 2023-09-16 17:32
Hi everyone, is this issue still being worked on? or is it abandonded? Could I still work this? Thanks!

**Comment by SaraJaoude** [comment] 2023-09-17 10:10
> Hi everyone, is this issue still being worked on? or is it abandonded? Could I still work this? Thanks!

@ArnabChatterjee20k ?

**Comment by ArnabChatterjee20k** [comment] 2023-09-24 16:51
> > Hi everyone, is this issue still being worked on? or is it abandonded? Could I still work this? Thanks!
> 
> @ArnabChatterjee20k ?

No I am going to work on it now only. I told in the discord. Actually I was suffering from some health issues. And my sister met an accident. So I was inactive. I am going to work on it right now

**Comment by ArnabChatterjee20k** [comment] 2023-10-01 03:55
I am actually confused about whether this issue is closed or not. I made a pr some hours ago. Actually I am working on it.

**Comment by SaraJaoude** [comment] 2023-10-25 20:27
@ArnabChatterjee20k as there has been no activity for some time I have unassigned you from this issue, but we look forward to you contributing when you can on another issue.

**Comment by mianakbarjan** [comment] 2023-10-26 07:38
Hi there, can this issue be assigned to me so I can start working on it?

**Comment by eddiejaoude** [comment] 2023-10-26 07:54
Sorry @SaraJaoude this is partly my fault, we were undecided about having 2 types of searches because locally we cannot have fulltext search like we do on Monog Atlas.

Thank you @ArnabChatterjee20k for your efforts on this issue and pull request.

But I will close this issue for now until we can think of a better way to have our local dev environment the same as production for search

**Closed by eddiejaoude** 2023-10-26 07:54 UTC
Labels: 💻 aspect: code, 🏁 status: ready for dev, 🔢 points: 5
